### ISSUE TITLE
Double '/' in path

### ISSUE THREAD

**Issue by scrwdnet** [spatie/temporary-directory#11]
When using this package through Media Library I get a double slash in the path generated by this line:

https://github.com/spatie/temporary-directory/blob/master/src/TemporaryDirectory.php#L88

Removing the ` .DIRECTORY_SEPARATOR. ` part fixed it for me.

**Comment by AlexVanderbist** [comment]
Hi! Thanks for reporting this. The issue is should be fixed in 1.1.3!
