### ISSUE TITLE
deleteDirectory returns true if directory does not exis

### ISSUE THREAD

**Issue by Gummibeer** [spatie/temporary-directory#16]
https://github.com/spatie/temporary-directory/blob/e3da5b7a00c6610bc0b18480815fe09adf73383b/src/TemporaryDirectory.php#L160-L162
If the directory I want to delete does not exist the delete itself was not successful. Now it's something philosophic if I still want to get `true` in this case. But how about throwing an exception `DirectoryDoesNotExistException`? This could be catched and used how ever you want.

**Comment by freekmurze** [comment]
Changing this now would be a breaking change. I'll consider this question when creating a new major version.
