### ISSUE TITLE
deleteDirectory deletes given path also if it is a file

### ISSUE THREAD

**Issue by Gummibeer** [spatie/temporary-directory#17]
https://github.com/spatie/temporary-directory/blob/e3da5b7a00c6610bc0b18480815fe09adf73383b/src/TemporaryDirectory.php#L164-L166

If the path I put in isn't a directory but a file it should not delete it - the request is to delete a directory and not a file.

I see the point in why it needs this behaviour, cause it's calling itself recursive. But in this case I think it should be renamed to something like `deleteChild`, `deleteElement` or something like this.

**Comment by freekmurze** [comment]
I think this is fine given the context that it calls itself recursively.

If you have some non-breaking improvement in mind, feel free to send a PR.

**Comment by Gummibeer** [comment]
Renaming it wouldn't be breaking cause it's protected!?

**Comment by freekmurze** [comment]
Indeed.
