### ISSUE TITLE
create has useless file_exists check

### ISSUE THREAD

**Issue by Gummibeer** [spatie/temporary-directory#18]
https://github.com/spatie/temporary-directory/blob/e3da5b7a00c6610bc0b18480815fe09adf73383b/src/TemporaryDirectory.php#L43-L45

It will never happen that it doesn't get into this if, three lines above you throw an exception if the file exists. Cause there is no other condition this is the same like an `else` or nothing around it cause the method breaks inside the first if (exception).

**Comment by freekmurze** [comment]
Good point, I'll change this.
