### ISSUE TITLE
make() method is undocumented

### ISSUE THREAD

**Issue by openjck** [spatie/temporary-directory#73]
I was reading the source code and noticed that the `make` method is shorthand for the following:

```php
(new self($location))->create();
```

I'm inclined to use this in our project because it's shorter. (At the moment, we have a trait which creates and returns a `TemporaryDirectory` object because the above is a bit unwieldy.) However, the `make` method is not documented, and therefore, I'm slightly concerned that it may not be supported in the future.

Will the `make` method be supported in the future? If so, should it be documented? I'm happy to submit a PR mentioning `make` depending on the answers to those questions.

**Comment by freekmurze** [comment]
The `make` method is here to stay, feel free to document it 👍
