### ISSUE TITLE
Suggestion: Delete directory on __destruct

### ISSUE THREAD

**Issue by sailingdeveloper** [spatie/temporary-directory#9]
It might not be useful in every case, but you could leverage the `__destruct()` method of php on the `TemporaryDirectory` class to automatically delete the folder at the end of the request/runtime. Willing to write a PR implementing this functionality

**Comment by freekmurze** [comment]
Thank you for your suggestion but I would not pull such a PR in.

Though there certainly may be use cases, adding this right now is a breaking change. I'll come back to this when creating a new major version. Could be a while though.

**Comment by k0ka** [comment]
V2 was released but this suggestions wasn't taken in account. 
I guess the temporary directory must be automatically deleted (or at least has a config key to enable it)
